/**
 * Changelog - Diario de novedades.
 * Siempre lo mas nuevo arriba.
 */
const Changelog = [
    {
        date: '30/05/2026 (sesion 3 — Stores Edition)',
        items: [
            { type: 'change', text: 'Editor de Grupos de tiendas rediseñado igual que el de familias: arriba chips de grupos (clic = activar, con contador y boton Eliminar), abajo el editor del grupo activo con sus tiendas en grid de chips (cada uno con "✕" para quitar). Boton "Renombrar" junto al titulo. Adios al editor inline con checkboxes' },
            { type: 'fix', text: 'Configuracion de grupos de tiendas: cada accion tardaba ~2 segundos. Causa: renderSettingsStoreGroups llamaba a Database.getDistinctValues(\'store\') tras cada toggle, y esa funcion recorre el indice completo de operations en IndexedDB (varios millones de filas → ~1-2s por llamada). Ahora Database cachea los resultados por field y los invalida automaticamente junto con opsCache en cada mutacion. Misma optimizacion beneficia a getDistinctValues(\'category\') y demas usos' },
            { type: 'change', text: 'Catalogo de tiendas como parrilla clickable en lugar de dropdown: bajo los chips del grupo activo, una parrilla con todas las tiendas conocidas; las que estan en el grupo aparecen resaltadas con ✓. Pulsa cualquier tienda para anadirla o quitarla del grupo. El buscador filtra ambas vistas. Las celdas fluyen alfabeticamente por COLUMNA (top-to-bottom), no por fila, para que la lectura sea natural' },
            { type: 'change', text: 'Editor de Familias de categorias: las familias ahora son una clasificacion del usuario PARALELA a las supercategorias (que siguen siendo fijas del catalogo CeX). El usuario crea sus propias familias desde cero y asigna categorias libremente. Setting categoryFamilies con forma limpia { families, assignments }. UI master-detail: chips de familias arriba (+ chip discontinuo "Sin familia"), abajo la familia activa con sus categorias en grid y selector "Mover a..."' },
            { type: 'new', text: 'Vista detalle: tercera opcion "Familia" en el toggle Categoria | Supercategoria | Familia, mas un multi-select "Familias" para filtrar. Permite analizar por la agrupacion del usuario igual que ya se hacia por supercategoria' },
            { type: 'fix', text: 'Editor de Familias: la pseudo-familia "Sin familia" ya muestra correctamente las categorias sin asignar (antes salia vacia por desajuste entre el sentinel interno y la label visible)' },
            { type: 'change', text: 'Editor de Familias: el dropdown "Mover a..." y el selector "+ Anadir categoria" se han sustituido por una parrilla clickable estilo Grupos de tiendas. Cada categoria es un boton con tres estados: ✓ en la familia activa (azul), → en otra familia (con badge del nombre), + sin familia (vacio). Click = toggle: anade, quita o mueve desde otra familia segun corresponda' },
            { type: 'change', text: 'Configuracion reorganizada en 6 pestañas: Calendario, Filtro ecom por KPI, Renombrado captacion, Grupos de tiendas, Familias de categorias, Mantenimiento (info BD + limpieza por fuente + restablecimiento + Drive). La pestaña activa se persiste — al volver a Configuracion te lleva a la que estabas viendo' },
            { type: 'new', text: 'Configuracion: nueva seccion "Grupos de tiendas". Toda la gestion (crear, renombrar, editar miembros con buscador y todas/ninguna, eliminar) vive aqui. En Vista general y Vista detalle queda solo el selector "Aplicar grupo" (read-only respecto a la edicion) — los botones inline de Guardar/Gestionar se han retirado para que los presets tengan un unico lugar de origen' },
            { type: 'new', text: 'Configuracion: nueva seccion "Familias de categorias". Editor completo (anadir familias propias, ocultar/eliminar familias incluyendo las de fabrica, reasignar cada categoria a la familia que prefieras). Las familias de fabrica viven en data/categories-supercategories.json y NO se modifican; las decisiones del usuario se persisten en setting categoryFamilies como overrides (mismo patron que los aliases de captacion). Cualquier cambio se refleja en Vista detalle al instante' },
            { type: 'change', text: 'Familias borradas: las categorias que tenian esa familia caen automaticamente a "Sin mapear" en Vista detalle hasta que se les asigne otra. Reversible: restaurar la familia las recupera con su asignacion previa' },
            { type: 'change', text: '% Attachment con umbrales propios (>=85 verde, 80-84 amarillo, <80 rojo) en lugar de los genericos 40/30. La columna aparece por defecto en Vista general y en compare mode de Vista por tienda, junto a la cuenta operaciones-con-socio / operaciones-totales que conforman el ratio' },
            { type: 'change', text: 'Vista por tienda: los tres KPIs de attachment (% Attachment, Ventas con socio, Transacciones (attachment)) aparecen ahora dentro del optgroup "Captacion" del selector de metrica, junto a Socios' },
            { type: 'fix', text: 'Parser Attachment descarta StoreName de departamentos no-tienda (ES Commerce, ES Ecomdistribution, RMA centres). Antes daba aviso "tienda sin match" porque buscaba el nombre en Baby Banking. Helper isNonStoreDept compartido entre Baby Banking y Attachment: cubre "commerce" (engloba "Ecommerce" y "Commerce"), "ecomdistribution" y "rma"' },
            { type: 'fix', text: 'Vista general y Vista por tienda (tabla y selector de tienda) filtran defensivamente cualquier tienda que sea en realidad un departamento (ES Ecommerce, RMA, etc.) aunque se haya colado en operations por un import previo. CSVParser.isNonStoreDept se reutiliza desde la app para coherencia' },
            { type: 'new', text: 'KPI "Attachment" activado. Nuevo dropzone "Attachment" (CSV de Looker, pestaña "Store Membership Attachment", ES + IC en un solo archivo). El parser splittea por columna Region en dos fuentes — attachment (ES) y attachment-ic (IC) — y descarta StaffID/StaffName (GDPR) sumando los contadores por (tienda, semana). El % se RECALCULA a nivel tienda como attachment_transactions / sale_transactions; el Percentage precalculado del CSV no se guarda' },
            { type: 'new', text: 'Tres KPIs nuevos: Transacciones (attachment), Ventas con socio, % Attachment. Disponibles en Vista por tienda (single y compare) y en el selector de columnas de Vista general. En Vista detalle no aplican (el attachment no tiene categoria de producto)' },
            { type: 'new', text: 'Cross-check no-bloqueante al importar Attachment: por cada (tienda, semana) se comparan las Transactions del CSV con los Order Numbers unicos de venta en tienda de Baby Banking. Util para validar que la numeracion de semanas del Looker (CeX) coincide con la del proyecto (sabado-viernes). Solo es un aviso informativo, no bloquea' },
            { type: 'new', text: 'Tabla nueva en Dexie: attachment_weekly (v2). PK natural (store, cycleYear, week, source), upsert por put — re-importar la misma semana sobreescribe sin duplicar. Reconciliacion de nombres de tienda reutiliza el reconciler y los alias de captacion (data/captacion-store-aliases.json)' },
            { type: 'change', text: 'Schema MySQL (docs/db-schema-stores.sql) ampliado: nueva tabla attachment_weekly con PK natural y chk_attach_qty (attachment <= transactions), nueva fuente attachment-ic en chk_imports_source. attachment/attachment-ic NO entran en operations.type ni operations.source: tienen su propia tabla por granularidad semanal' },
            { type: 'new', text: 'Tests de regresion para el parser attachment: 10 casos cubriendo agregacion ES/IC, descarte de Percentage, validacion de Transactions/Attachment numericos, y GDPR (staff/staffId/staffName nunca entran al record, incluso con mapping malicioso)' },
            { type: 'change', text: 'Backup JSON (export/import) incluye attachment_weekly. Backups antiguos sin esa tabla siguen siendo importables (campo opcional)' },
            { type: 'change', text: 'Panel "Limpiar datos por fuente" sabe limpiar attachment y attachment-ic en su tabla propia. Coverage del Home muestra ambas fuentes con su rango de semanas convertido a sabado-viernes para encajar con las demas barras' },
        ]
    },
    {
        date: '26/05/2026 (sesion 2 — Stores Edition)',
        items: [
            { type: 'new', text: 'Fase 3 DESPLEGADA: la app esta corriendo en https://capimetrics.cexsv.com/ (FTP de Hostinger, dominio + HTTPS proporcionados por David). Subdominio interno corporativo. Bloqueo de indexacion verificado en produccion: robots.txt, meta noindex y header HTTP X-Robots-Tag activos via LiteSpeed' },
            { type: 'new', text: 'Preparacion fase 3: añadidos robots.txt, meta noindex/nofollow en index.html y plantilla de .htaccess con X-Robots-Tag, bloqueo de archivos sensibles y bloque Basic Auth comentado. Objetivo: que la herramienta corporativa pase totalmente desapercibida en buscadores' },
            { type: 'new', text: 'Schema MySQL definitivo (docs/db-schema-stores.sql) redactado para la stores edition. Adapta la propuesta corporativa del PDF (docs/db-schema.md) eliminando staff (GDPR), simplificando roles a admin/viewer y traduciendo a sintaxis MySQL. Listo para ejecutar en la BD u782235572_CPMT (vacia hasta hoy)' },
            { type: 'change', text: 'Hoja de ruta (CLAUDE.md) ampliada con el plan completo de auth para fase 4: Google OAuth + RBAC desde el dia uno (admin / viewer) sobre el schema MySQL. Decision firme: una sola app con roles, NO dos versiones del codigo' },
        ]
    },
    {
        date: '19/05/2026 (sesion 1 — Stores Edition)',
        items: [
            { type: 'new', text: 'Bifurcacion: KPI Metrics 2026 edicion solo-tiendas (repo aparte: KPIMetrics-Stores). Version derivada de KPITool2026 que descarta el campo Staff del CSV y elimina toda la vista por empleado y los KPIs por staff. Captacion de socios y admision a test SIGUEN existiendo, pero ahora son siempre a nivel de tienda. Cumple GDPR: la base de datos local nunca contiene identificadores de empleado en ninguna fuente' },
            { type: 'change', text: 'DB Dexie renombrada de "KPITool2026" a "KPIMetricsStores2026". Los backups exportados desde el repo padre NO son compatibles con esta edicion y no deben importarse. Schema v1 limpio (sin migraciones acumuladas, sin indices por staff)' },
            { type: 'new', text: 'Tests de regresion GDPR: el parser nunca produce campo staff (ni en Baby Banking ni en captacion, incluso si el mapping lo incluye), y ningun KPI registrado contiene staff/empleado en id o nombre. Si alguien intenta reintroducir staff, los tests fallan al commitear (pre-commit hook)' },
            { type: 'remove', text: 'Vista tienda/empleado pasa a llamarse "Vista por tienda". Fuera el selector scope (Por empleado / Por tienda), el buscador de empleados, el toggle "Unificar tiendas" y la atribucion por staff en el bucket. Cash buy / exchange / refund EUR vuelven a sumar siempre (la supresion era exclusiva de scope=staff)' },
            { type: 'change', text: 'Captacion de socios: el importador, el KPI "Socios" y el reconciler de aliases de tienda se mantienen. Lo unico que cambia es que la columna Staff del CSV ya no se guarda (cada socio queda atribuido a tienda + fecha)' },
            { type: 'change', text: 'Captacion almacenada agregada por (tienda, dia): una fila con quantity=N socios captados ese dia en esa tienda, en vez de N filas individuales. Compresion ~10x para esa fuente sin perder informacion (sin Order Number, Member Id ni Staff, las filas individuales eran indistinguibles)' },
            { type: 'change', text: 'Admision a test: las filas Transfer/Test siguen sobreviviendo como type=test-admission y los KPIs Ordenes de test / Items admitidos / Ratio de ordenes de test se mantienen, ahora a nivel de tienda en vez de por staff' },
        ]
    },
    {
        date: '05/05/2026 (sesion 9)',
        items: [
            { type: 'new', text: 'Configuracion: panel "Limpiar datos por fuente" (configuracion profunda). Permite borrar las filas y el historial de importaciones de UNA fuente concreta (Baby Banking ES, Baby Banking IC, Captacion, etc.) sin afectar a las demas ni a la configuracion. Para Ecom no hay filas propias: limpiarlo desetiqueta las filas Baby Banking marcadas como ecom y borra el historial de importaciones de Ecom. Confirmacion obligatoria. Nada que toque settings (course start, ecom-per-KPI, aliases de captacion)' },
            { type: 'new', text: 'KPIs de Admision a test. Las filas de Baby Banking ES e IC con type=Transfer y category="Test"/"TEST" dejan de descartarse: se importan como un tipo nuevo (test-admission) que alimenta tres metricas — Ordenes de test (Order Numbers unicos), Items admitidos a test (suma de Quantity) y Ratio de ordenes de test (ordenes de test / total de operaciones de mostrador del staff/tienda). El resto de filas Transfer (movimientos internos de stock) se siguen descartando' },
            { type: 'new', text: 'Familia de KPIs "Operaciones": cuenta cuantas ordenes de mostrador hace cada staff/tienda y de que tipo. Operaciones (total), Refunds (n), Cash buys (n) y Exchanges (n). Tickets sigue contando solo ventas; "Operaciones" agrega tambien las que no son venta. Una misma orden puede contener compras y ventas a la vez: cada movimiento cuenta una unica vez en su propia metrica' },
            { type: 'change', text: 'Bucket de Vista tienda/empleado refactorizado: en scope=staff las filas cash buy / exchange / refund vuelven al bucket pero con su importe en EUR suprimido (decision preexistente: solo sale y test-admission son atribuibles al staff). Sus Order Numbers si entran en counterRefs y en sets per-tipo, lo que permite las metricas Operaciones y un denominador correcto para Ratio de ordenes de test. Las metricas existentes del staff (Tickets, Ventas, Refunds EUR, etc.) no cambian de comportamiento' },
            { type: 'new', text: 'Vista tienda/empleado: tooltip de descripcion en cada KPI. En modo comparar, la celda con el nombre del KPI muestra al pasar el raton la misma descripcion que ya tiene Vista general. En modo simple, un boton de info junto al selector de KPI abre un popover con la formula del KPI activo' },
            { type: 'change', text: 'Importadores ES e IC: actualizado el aviso del popover para reflejar que las filas Transfer/Test ya no se descartan' },
            { type: 'change', text: 'Vista detalle: filas con type="test-admission" se filtran al inicio del loop de categorias (la "Test" de admisiones no es una categoria de producto)' },
            { type: 'change', text: 'Data Explorer: filtro de tipo de transaccion incluye "Admision a test"' },
            { type: 'change', text: 'Selector de KPIs en Vista tienda/empleado: nuevos grupos "Admision a test" y "Operaciones"' },
            { type: 'fix', text: 'Rebrand: "KPI Metrix 2026" → "KPI Metrics 2026". El nombre anterior era un typo. El identificador interno (DB Dexie, carpeta de backup en Drive) sigue siendo "KPITool2026" para no romper datos existentes' },
        ]
    },
    {
        date: '03/05/2026 (sesion 8)',
        items: [
            { type: 'new', text: 'Importador de Captacion de socios activado. CSV de Looker (pestaña "New Store Membership", ES + IC). Cada fila = un socio captado por staff/tienda en una fecha. Member Id y Operating Company se descartan al importar para anonimizacion: la herramienta solo guarda que ese dia ese staff capto un socio' },
            { type: 'new', text: 'Importador de captacion: politica de reemplazo por rango. Cada importacion borra los socios previos cuyas fechas caen dentro del CSV nuevo y los sustituye. Re-importar no duplica filas' },
            { type: 'new', text: 'KPI "Socios" en Vista general (selector de columnas), Vista tienda/empleado (modo individual y compare) y barra de cobertura del Home. La columna placeholder "Socios" en Vista general deja de ser placeholder' },
            { type: 'new', text: 'Reconciliacion automatica de nombres de tienda en captacion contra Baby Banking. Cascada: quita prefijo "CeX ", ignora tildes, mayusculas y espacios. Para discrepancias mayores (palabras distintas, erratas) hay un set de aliases manuales precargado en data/captacion-store-aliases.json' },
            { type: 'new', text: 'Configuracion: editor de aliases de tienda colapsable con aviso "configuracion profunda" y mailto al desarrollador (abeatrice@webuy.com). Permite anadir, sobrescribir o restaurar aliases. Cualquier cambio reaplica al instante el reconciler a las filas ya importadas, sin re-importar' },
            { type: 'new', text: 'Drop zone placeholder para Attachment (% de ventas en tienda realizadas con socio). Mismo Looker que captacion, pestaña "Store Membership Attachment", ES + IC. Implementacion pendiente' },
            { type: 'change', text: 'Importador rediseñado: 6 drop zones cuadrados, compactos (150px) y centrados horizontalmente con grid auto-fit. Antes los cards eran rectangulos que ocupaban todo el ancho. Cards igualados en altura aunque algunos tengan solo una linea de descripcion' },
            { type: 'change', text: 'Barras de cobertura del Home reducidas en altura (~30%) para que las 6 fuentes quepan sin scroll en pantallas full HD' },
            { type: 'new', text: 'Popovers de info de drop-zones: detectan al hover si hay sitio arriba; si no, se abren hacia abajo. Antes podian quedar ocultos por la barra del navegador' },
            { type: 'new', text: 'Popovers escalan con scroll vertical interno cuando el contenido excede la altura disponible (max-height: calc(100vh - 80px))' },
            { type: 'fix', text: 'Popovers: las palabras en negrita ahora se ven. Cascada CSS .import-zone strong forzaba color oscuro sobre fondo oscuro del popover y las palabras destacadas quedaban invisibles' },
            { type: 'change', text: 'Popovers: z-index subido a 1000 y el card padre se eleva mediante :has() mientras el boton i esta activo, para que no queden por detras de cards adyacentes. Espaciado vertical uniformizado entre headings y texto' },
            { type: 'change', text: 'Vista detalle: filas con type="membership" se filtran al inicio del loop para no contaminar la lista de categorias (los socios no tienen categoria)' },
            { type: 'change', text: 'Data Explorer: filtro de tipo de transaccion incluye "Captacion de socios" (membership) para inspeccionar las filas importadas' },
        ]
    },
    {
        date: '23/04/2026 (sesion 7)',
        items: [
            { type: 'new', text: 'Vista tienda/empleado: modo comparar KPIs. Al fijar una sola tienda o empleado, la tabla cambia a filas=KPIs, columnas=semanas, con sparkline por fila. Multi-select de KPIs para elegir cuales comparar (6 por defecto)' },
            { type: 'new', text: 'Vista tienda/empleado: selector de empleado buscable (cuando scope=empleado) para entrar en modo comparar' },
            { type: 'fix', text: 'Vista tienda/empleado: el grafico de evolucion ya se muestra correctamente. Error silencioso (Y_AXIS_WIDTH indefinido) rompia el render de Chart.js y lo dejaba vacio' },
            { type: 'new', text: 'Vista tienda/empleado: cuando hay varios empleados/tiendas en el grafico, se muestra siempre una linea dasheada gris con el total agregado para dar contexto' },
            { type: 'fix', text: 'Vista tienda/empleado: tooltip del icono de info del grafico ya no se duplica (title nativo + custom al mismo tiempo) ni se corta con el borde del panel' },
            { type: 'new', text: 'Configuracion: filtro ecom por KPI. Cada KPI decide si incluye o excluye las ordenes de e-commerce. Se retira el switch "Filtrar ecom" de las 3 vistas. Por defecto: KPIs de volumen (Ventas, Refunds, Articulos) incluyen ecom; los de comportamiento presencial (Tickets, % Venta compl., % Gel/Mvl, etc.) lo excluyen' },
            { type: 'new', text: 'Vista general: filtro multi-select de tiendas (antes no tenia filtro propio de tiendas)' },
            { type: 'new', text: 'Vista general: grupos de tiendas guardables. Crea "Zona Norte", "Canarias", etc., aplicalos con un click. Se pueden renombrar, actualizar y eliminar. Compartidos con Vista detalle' },
            { type: 'new', text: 'Vista general: nuevas columnas % Venta compl., % Gel/Mvl, % Basics/Mvl. Se retiran los placeholders KPI 1-5. Socios y Stock se mantienen como placeholders' },
            { type: 'new', text: 'Vista general: selector de KPIs configurable. Eliges que columnas ver y en que orden (botones arriba/abajo). "Por defecto" resetea' },
            { type: 'change', text: 'Vista general: el TOTAL recalcula medias ponderadas correctas sobre el subconjunto visible de tiendas (no una suma ingenua)' },
            { type: 'new', text: 'Vista detalle: filtro por supercategoria. Mapping de 231 categorias a 7 supers (Juegos, Electronica, Informatica, Moviles, DVD, Accesorios Nuevos, Other), cargado desde data/categories-supercategories.json' },
            { type: 'new', text: 'Vista detalle: segmented control para elegir granularidad (Categoria o Supercategoria) - unicamente uno de los dos filtros esta activo a la vez' },
            { type: 'new', text: 'Vista detalle: boton swap para intercambiar ejes. Por defecto tiendas en filas y grupos en columnas; al pulsar, grupos en filas y tiendas en columnas. Util para comparar dos tiendas concretas' },
            { type: 'new', text: 'Vista detalle: boton de info (i) junto al filtro de categorias. Abre un popover con el mapa completo supercategoria -> categorias, con buscador. Solo lectura' },
            { type: 'new', text: 'Vista detalle: grupos de tiendas compartidos con Vista general. Los grupos que guardes en cualquiera de las dos vistas aparecen en ambas' },
            { type: 'change', text: 'Cabeceras de paneles: titulo + filtros ya no se estiran a los extremos. Ambos se agrupan centrados, alineados con la tabla centrada del body' },
            { type: 'change', text: 'Linea "Datos disponibles..." reubicada junto al titulo del modulo (section-header), fuera del area de trabajo. Quita ruido visual' },
            { type: 'new', text: 'Favicon (assets/favicon.png)' },
        ]
    },
    {
        date: '23/04/2026 (sesion 6)',
        items: [
            { type: 'new', text: 'Activado importador Baby Banking IC (Islas Canarias): parser reconoce headers IC (branchname, order_date, box_id, box_name, boxcategory)' },
            { type: 'change', text: 'Filtro de branches no-tienda (RMA, Ecomdistribution, Ecommerce) ahora es generico: captura variantes ES e IC' },
            { type: 'new', text: 'Drop zone de Baby Banking IC con link a Looker (dataset IC) e info sobre el proceso de importacion' },
            { type: 'new', text: 'Drop zone de Ecom Sales con link a Looker e info (incluye instruccion de filtrar region a ES+IC al exportar)' },
            { type: 'fix', text: 'Barra de cobertura de Ecom ahora muestra solo el rango efectivamente aplicado (interseccion con BB ES+IC). Los dias de Ecom sin BB que cruzar no cuentan como cobertura' },
            { type: 'new', text: 'Label "Datos disponibles" en los 3 dashboards: indica desde que W/año hasta cual hay datos cargados, con fechas de referencia' },
            { type: 'change', text: 'Auto-rellenado de rango de semanas: al abrir un dashboard por primera vez, los inputs se ajustan al rango de datos disponibles en lugar de 1-15 hardcoded' },
            { type: 'change', text: 'Vista detalle: selector de semana unica sustituido por rango (De W / a W). Suma metricas a lo largo del rango y muestra TOTAL por fila/columna. Tickets se contabilizan con Set de referencias unicas para evitar inflar totales cuando una orden abarca varias categorias' },
            { type: 'new', text: 'Vista detalle: filtros multi-select con checkbox para categorias y tiendas. Por defecto se muestran las 5 categorias top de la metrica activa; si cambias de metrica y no has tocado el filtro, se recalcula el top 5. Boton "Top 5 por metrica" para resetear la seleccion' },
            { type: 'new', text: 'Vistas general y detalle: click en cabecera de columna para ordenar. Primer click descendente, clicks sucesivos alternan' },
            { type: 'change', text: 'Vista general: filtro "Filtrar ecom" desactivado por defecto (antes venia activado)' },
            { type: 'fix', text: 'Performance: cache en memoria de la tabla de operaciones. Antes cada click de filtro/sort/cambio de metrica releia TODA la BD. Ahora solo se lee al arrancar o tras un import/restore/reset. Mejora drastica en interacciones (~10-20x mas rapido)' },
        ]
    },
    {
        date: '22/04/2026 (sesion 5 - parte 2)',
        items: [
            { type: 'change', text: 'Nombre de la app: KPI Tool 2026 -> CapiMetrics 2026 (topbar, titulo, backups). BD interna conserva el nombre anterior por compatibilidad' },
            { type: 'change', text: 'Home: saludo "Buenos dias" retirado, sustituido por logo de CapiMetrics (assets/logo.png)' },
            { type: 'change', text: 'Home armonizado con CapiTool: cards mas pequeñas (~15%) y con mismo formato horizontal en todas las secciones' },
            { type: 'change', text: 'Layout del home: Vistas arriba centradas, Cobertura + Data en 2 columnas debajo' },
            { type: 'change', text: '"Herramientas" renombrado a "Data"' },
            { type: 'change', text: 'Iconos de Data con colores: Configuracion ambar, Exportar violeta, Importar backup rosa, Google Drive verde' },
            { type: 'change', text: 'Contador de tiendas movido del saludo al label de Cobertura ("COBERTURA · N tiendas")' },
            { type: 'change', text: 'Distancia logo -> primera fila de cards reducida un 20%' },
            { type: 'new', text: 'Drop zone "Baby Banking IC" para Islas Canarias (inactiva hasta resolver diferencias de formato con ES)' },
            { type: 'new', text: 'Drop zone "Stocks (AIO)" para inventario desde AIO (inactiva, pendiente formato)' },
            { type: 'change', text: 'Cobertura muestra todas las fuentes (BB ES, BB IC, Ecom, Captacion, Stocks); las vacias aparecen con "sin datos"' },
            { type: 'change', text: 'Cross-reference de Ecom preparado para cruzar contra ES + IC cuando IC se active' },
            { type: 'change', text: 'Drop zone Attachment eliminada del importador' },
        ]
    },
    {
        date: '22/04/2026 (sesion 5)',
        items: [
            { type: 'new', text: 'Dashboard semanal: 3 vistas desde el home (General, Detalle, Tienda/empleado)' },
            { type: 'new', text: 'Vista general (Tiendas x KPIs): rango de semanas, suma de ventas netas, compras y % vale' },
            { type: 'new', text: 'Vista detalle (Tiendas x Categoria): desglose por categoria segun metrica' },
            { type: 'new', text: 'Vista tienda/empleado: unifica los antiguos paneles Ventas y Moviles en un solo panel con selector de KPI' },
            { type: 'new', text: 'Selector de KPI agrupado por familia (Ventas, Moviles, Compras) - preparado para ir añadiendo mas' },
            { type: 'new', text: 'Calculo de ventas netas: brutas menos refunds' },
            { type: 'new', text: 'Calculo de compras: cash buy + exchange, con % pagado en vale de tienda' },
            { type: 'new', text: 'Home reorganizado: solo 3 cards de vistas arriba, herramientas a la derecha (Importar CSV incluido)' },
            { type: 'change', text: 'Eliminadas secciones independientes de Ventas y Moviles. Su funcionalidad vive en Vista tienda/empleado' },
            { type: 'change', text: 'Importador: los refunds pasan a guardarse (antes se descartaban). Reimporta los CSV para disponer de ellos' },
            { type: 'change', text: 'Columnas pendientes (Socios, Stock, KPI 1-5) quedan como placeholders hasta definir origen' },
        ]
    },
    {
        date: '09/04/2026 (sesion 4)',
        items: [
            { type: 'new', text: 'KPI Ventas: tickets, articulos, facturacion, ventas multiples, % venta complementaria, media articulos/ticket' },
            { type: 'new', text: 'Home rediseñado: cards verticales 3:4 con icono, nombre y listado de metricas' },
            { type: 'new', text: 'Cobertura de datos en Home: barras por fuente (Baby Banking, Ecom) con fechas' },
            { type: 'new', text: 'Columna Tienda en tablas de evolucion con indicador de empleados multi-tienda (*)' },
            { type: 'new', text: 'Switch Unificar: fusiona apariciones del mismo empleado en varias tiendas' },
            { type: 'new', text: 'Columna de ranking (#) en todas las tablas de KPIs' },
            { type: 'new', text: 'Filtro minimo de operaciones para metricas porcentuales (configurable)' },
            { type: 'new', text: 'Heatmap gradual azul en celdas de metricas absolutas' },
            { type: 'new', text: 'Verificar datos: filtros por tienda, categoria, canal, fechas' },
            { type: 'new', text: 'Top 20 en selector de ranking' },
            { type: 'new', text: 'Scope "Por tienda" reemplaza "Total tienda" en evolucion' },
            { type: 'fix', text: 'Restablecer herramienta ahora borra la BD completamente (Dexie.delete)' },
            { type: 'fix', text: 'Importador filtra departamentos no-tienda (RMA, Ecomdistribution, Ecommerce)' },
            { type: 'fix', text: 'Totales de facturacion en Ventas calculados correctamente' },
            { type: 'fix', text: 'Filtrar ecom activado por defecto' },
            { type: 'new', text: 'Barra de progreso global al restaurar backups (overlay con porcentaje)' },
        ]
    },
    {
        date: '08/04/2026 (sesion 3)',
        items: [
            { type: 'new', text: 'Importador Ecom Sales activo: cruza ordenes ecom con Baby Banking y marca canal (ecom/tienda)' },
            { type: 'new', text: 'Campo "channel" en registros: distingue ventas en caja vs e-commerce' },
            { type: 'new', text: 'Switch "Solo tienda" en evolucion semanal: excluye ordenes ecom de los KPIs' },
            { type: 'new', text: 'Timeline de cobertura ecom con fechas de inicio/fin por tramo y huecos sin cobertura' },
            { type: 'new', text: '4 drop zones independientes en fila (Baby Banking, Ecom, Attachment, Captacion)' },
            { type: 'new', text: 'Hint contextual en cada drop zone (ej: "Datos globales, todas las tiendas")' },
            { type: 'new', text: 'Filas ecom sombreadas en violeta tenue en el explorador de datos (Verificar datos)' },
            { type: 'new', text: 'Columna Total sombreada en tabla de evolucion para diferenciarla de semanas' },
            { type: 'new', text: 'Escala del eje Y visible en el grafico, alineada en la columna previa' },
            { type: 'fix', text: 'Mapping Ecom Sales con fuzzy match: detecta headers con sufijos variables' },
            { type: 'fix', text: 'DB v5: index "source" en nueva version (Dexie no re-aplica schemas existentes)' },
            { type: 'fix', text: 'Init robusto: bindEvents siempre se ejecuta aunque falle la carga de settings' },
        ]
    },
    {
        date: '08/04/2026 (sesion 2)',
        items: [
            { type: 'new', text: 'Grafico de evolucion semanal con Chart.js: lineas por empleado o total tienda' },
            { type: 'new', text: 'Click en fila de la tabla para ver su grafico individual (+ total como referencia en linea discontinua)' },
            { type: 'new', text: 'Fila TOTAL tambien seleccionable para grafico' },
            { type: 'new', text: 'Selector Top N (Top 3, 5, 10, Todos) en filtros de evolucion: filtra tabla y grafico' },
            { type: 'new', text: 'Tooltip info (i) en el grafico explicando numerador/denominador de cada metrica' },
            { type: 'new', text: 'Panel unico de Moviles: eliminado resumen redundante, solo evolucion semanal con todos los filtros' },
            { type: 'new', text: 'Rango de semanas persistido en IndexedDB (se recuerda entre sesiones y en backups)' },
            { type: 'new', text: 'Explorador de datos movido dentro de Importar CSV como boton "Verificar datos" desplegable' },
            { type: 'new', text: 'Home: resumen muestra "Todo" por defecto al cargar' },
            { type: 'new', text: 'Boton "Novedades" en topbar con modal de changelog' },
            { type: 'fix', text: 'Chart.js: URL corregida a cdn.jsdelivr.net (version 4.4.4, la anterior daba 404)' },
            { type: 'fix', text: 'Error btn-drive-auth eliminado (rompia toda la inicializacion al estar sombreado Drive)' },
            { type: 'fix', text: 'Variable allStaff declarada antes de usarse en renderEvoChart (error de referencia)' },
        ]
    },
    {
        date: '08/04/2026 (sesion 1)',
        items: [
            { type: 'new', text: 'Estructura base del proyecto: HTML/CSS/JS, IndexedDB (Dexie.js), Papa Parse' },
            { type: 'new', text: 'Home profesional con sidebar, topbar, panel resumen con filtros de periodo y tienda' },
            { type: 'new', text: 'Importador CSV adaptado al formato Baby Banking ES de Looker (12 columnas)' },
            { type: 'new', text: 'Multi-source: botones para Baby Banking, Ecom Sales, Attachment, Captacion (3 ultimos proximamente)' },
            { type: 'new', text: 'Historial de importaciones con metadata: archivo, origen, fecha, rango de datos, tiendas, filas' },
            { type: 'new', text: 'Deduplicacion por fuente al importar (misma orden de distinta fuente NO es duplicado)' },
            { type: 'new', text: 'Optimizacion de almacenamiento: solo campos KPI-relevantes, descarte de transfers y refunds' },
            { type: 'new', text: 'Backup comprimido .json.gz (pako.js). Importacion soporta .gz y .json' },
            { type: 'new', text: 'Nombre de exports con fecha y hora: kpitool_export_2026-04-08_1109.json.gz' },
            { type: 'new', text: 'Restablecer herramienta con doble confirmacion y recomendacion de backup previo' },
            { type: 'new', text: 'Calendario de negocio: semanas sabado-viernes, semana 1 = 27/12/2025, configurable' },
            { type: 'new', text: 'KPI Moviles con porcentajes, desglose de unidades y colores (>40% verde, 30-40% amarillo, <30% rojo)' },
            { type: 'new', text: '% Combo: indicador de venta conjunta de geles + basics por movil' },
            { type: 'fix', text: 'Calculo de semanas con Date.UTC para evitar desfase por cambio de hora (DST)' },
            { type: 'fix', text: 'Fechas siempre en DD/MM/AAAA, input de texto en vez de date picker nativo' },
            { type: 'fix', text: 'Botones de confirmar/cancelar importacion visibles arriba sin necesidad de scroll' },
            { type: 'new', text: 'Google Drive sombreado como "proximamente"' },
        ]
    }
];
